# Generated by Django 6.0.2 on 2026-02-22 22:42

import Stupac.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generic_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=32)),
                ('last_name', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', Stupac.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('generic_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_first_name', models.TextField(blank=True, max_length=32, null=True)),
                ('admin_last_name', models.TextField(blank=True, max_length=32, null=True)),
                ('admin_email', models.TextField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'admin',
            },
            bases=('Stupac.generic_user',),
            managers=[
                ('objects', Stupac.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pac',
            fields=[
                ('generic_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('pac_id', models.AutoField(primary_key=True, serialize=False)),
                ('pac_first_name', models.TextField(blank=True, max_length=32, null=True)),
                ('pac_last_name', models.TextField(blank=True, max_length=32, null=True)),
                ('pac_email', models.TextField(blank=True, max_length=64, null=True)),
                ('gender', models.TextField(blank=True, max_length=16, null=True)),
                ('department', models.TextField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'pac',
            },
            bases=('Stupac.generic_user',),
            managers=[
                ('objects', Stupac.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('generic_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_first_name', models.TextField(blank=True, max_length=32, null=True)),
                ('student_last_name', models.TextField(blank=True, max_length=32, null=True)),
                ('student_email', models.TextField(blank=True, max_length=64, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('course', models.CharField(blank=True, max_length=64, null=True)),
                ('assigned_pac', models.ForeignKey(db_column='assigned_pac', on_delete=django.db.models.deletion.CASCADE, to='Stupac.pac')),
            ],
            options={
                'db_table': 'student',
            },
            bases=('Stupac.generic_user',),
            managers=[
                ('objects', Stupac.models.CustomUserManager()),
            ],
        ),
    ]
