# Generated by Django 6.0.2 on 2026-02-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pac_id', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('dob', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('last_edited_when', models.TextField(blank=True, null=True)),
                ('last_edited_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pac',
                'managed': False,
            },
        ),
    ]
