# Generated by Django 6.0.2 on 2026-02-18 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stupac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pac',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='Stupac.admin'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, db_column='last_edited_by', null=True, on_delete=django.db.models.deletion.CASCADE, to='Stupac.admin'),
        ),
    ]
