# Generated by Django 6.0.2 on 2026-02-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stupac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='assigned_pac',
        ),
        migrations.AddField(
            model_name='student',
            name='pac_first_name',
            field=models.TextField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pac_last_name',
            field=models.TextField(blank=True, max_length=32, null=True),
        ),
    ]
