# Generated by Django 6.0.2 on 2026-02-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stupac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('course', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
